config/routes.rb
Rails.application.routes.draw do
  get 'cards/show'
  root "products#index"

  resources :products, only: [:index, :show]
  resources :cart_items
  resource :cards, only:[:show]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    before_save :set_subtotal

    def subtotal
      
       cart_items.collect{|cart_item| cart_item.valid? ?cart_item.unit_price*cart_item.quantity : 0}.sum
    end


    private
    def set_subtotal
      self[:subtotal] = subtotal  

    end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  before_save :set_unit_price
  before_save :set_total

  def unit_price
    
    if product.persisted?
      self[:unit_price] =product.price
    else
      product.price
  end
end

  def total
    
    unit_price * quantity
  end


  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :image, ImageUploader
    has_many :cart_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include ApplicationHelper

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @cart_items = current_order.cart_items
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
    
    def create 
        @cart= current_order
        @cart_item=@cart.cart_items.new(cart_params)
        @cart.save
        session[:cart_id] = @cart.id
        
       
    end


    def update

        @cart= current_order
        @cart_item=@cart.cart_items.find(params[:id])
        @cart_item.update_attributes(cart_params)
        redirect_to root_path
    end


    def show

        @cart= current_order
        @cart_item=@cart.cart_items.find(params[:id])
        @cart_item.destroy
        redirect_to root_path
    end

    private

    def cart_params
        params.require(:cart_item).permit(:product_id, :quantity)

    end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products=Product.paginate(page: params[:page], per_page: 2)
    @cart_item = current_order.cart_items.new
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


    def current_order
        if !session[:cart_id].nil?
            Cart.find(session[:cart_id])
        else
            Cart.new
        end
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cards/show.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand">Navbar</a>
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>

<div class="container mt-5 mb-5">
            <div class="d-flex justify-content-center row">
                <div class="col-md-8">
                    <div class="p-2">
                        <h4>Shopping cart</h4>


<br>

<% @cart_items.each do |item| %>
  <div class="card">
  <div class="card-header">
  <%= item.product.name%>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= item.product.description%></h5>
    <p class="card-text">Price: <%= item.product.price%></p>
    <%= form_for item do |f|%>
      <%= f.hidden_field :product_id, :value => item.product.id %>
      <%= f.number_field :quantity, :value => item.quantity.to_i%>
      <%= f.submit "Update cart" , class:"btn btn-primary "%>
      <br>
      <%= link_to "Destroy", cart_item_path(item), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } %>
      <h4>Subtotal: <%= item.total %></h4> 
    <%end%>
  </div>
</div>

  <br><br>    
    <% end %>

    <h5>You Current Cart value is  <%= current_order.subtotal%></h5>

    <a href="#" class="btn btn-primary">Check Out</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Commerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand">Food Mart</a>
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>
<br><br>
<div class="container">
<div class="row">

<% @products.each do |product| %>
  <div class="col-4"> 

<div class="card" style="width: 18rem;">
<%= image_tag product.image.url ,class:"card-img-top",width:"286",height:"180"%>
  <div class="card-body">
    <h5 class="card-title"><%= product.price%></h5>
    <p class="card-text"><%= product.name%></p>
   
    <%= form_for @cart_item do |f|%>
      <%= f.hidden_field :product_id, :value => product.id %>
      <%= f.number_field :quantity, :value => 1, :min => 1 %>
      <br><br>
      <%= f.submit "Add to cart",class:"btn btn-primary "%>
      
      <%= link_to "show", product_path(product),class:"btn btn-primary"%>
      
      <%end%>
    
  </div>
</div>


  
  </div>
<% end %>
</div>
</div>
<br><br>
<center>
<%= link_to "#{current_order.cart_items.size} items with a value of #{current_order.subtotal}$", cards_path%>
</center>


<%= will_paginate @products, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/products/show.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand">View Product</a>
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>
<br><br>
<main class="container1">
<div class="left-column">
<%= image_tag @product.image.url ,class:"w-50 p-5"%>
  </div>

  <div class="right-column">
 
    <!-- Product Description -->
    <div class="product-description">
      <span><%= @product.name %></span>
      <h1>Beats EP</h1>
      <p>The preferred choice of a vast range of acclaimed DJs. Punchy, bass-focused sound and high isolation. Sturdy headband and on-ear cushions suitable for live performance</p>
    </div>
 
  
 
    <!-- Product Pricing -->
    <h4>Price: </h4>
      <span><%= @product.price %></span>
      <br><br>
      <a href="#" class="btn btn-primary">Add to cart</a>
    </div>
  </div>
</main>


 
  
      
      
      
      <p><%= @product.description %></p>
      